### PR TITLE
Upgrade to Soy version 2016-08-09

### PR DESCRIPTION
**Pull request by andris-szatmari**
As a requirement for upgrading kinja-mantle to Play 2.4, this PR upgrades Soy to version 2016-08-09

### CODE REVIEW

**Review by balagez — APPROVED** [review]

**Review by ClaireNeveu — APPROVED** [review]

**Comment by ClaireNeveu** [comment]
CC @bregenspan Regarding closure template updates.

**Comment by andris-szatmari** [comment]
@ClaireNeveu i didn't find any projects for this and the play2-clouse one in jenkins. Do I need to publish manually from sbt?

**Comment by ClaireNeveu** [comment]
I set one up a while ago, it's possible it didn't make the transition to the new jenkins.

**Comment by ClaireNeveu** [comment]
@stratiator The jenkins job is here: http://jenkins-docker.kinja-ops.com:8081/view/All/job/soy/

**Comment by andris-szatmari** [comment]
Okay, i completely missed that searching for "soy" in jenkins actually opened the same page for me

**Pull request merged**
